### ISSUE TITLE
problem if the numbers of rows <10

### ISSUE THREAD

**Issue by dhekrazaied** [andrewroycarter/TimeScroller#11]
if the numbers of rows in the tableview is too small the timeScroller didn't appear in the correct frame,to test it just change the numbersofRows to 2 for example,how can i fix that please??

**Comment by andrewroycarter** [comment]
That's a good point.
There's a few ideas that come to mind to fix this, but in the mean time, you may be able to just to something like
timeScroller.hidden = numberOfRows < 10
Because if there's only a few rows, showing the time scroller seems unneeded anyway. I'll work out a fix though! Do let me know if you come up with a solution, and I'll accept a pull request!

**Comment by dhekrazaied** [comment]
that's what i do like a temprary solution but we have to find an efficient one

**Comment by andrewroycarter** [comment]
I've got a pull request to review that's supposed to fix this issue and also add some other functionality.
